### PR TITLE
Bump 6to5 to 2.12.5

### PR DESCRIPTION
**Pull request by hhff**

### CODE REVIEW

**Comment by hhff** [comment]
for posterity: https://github.com/ember-cli/ember-cli/issues/2999

**Comment by stefanpenner** [comment]
thanks!  published as broccoli-6to5-transpiler@2.0.4

**Comment by hhff** [comment]
thanks @stefanpenner !

**Comment by thejameskyle** [comment]
For future reference, these kinds of bumps aren't necessary since the `^` operator will match up to the next major version.

**Comment by stefanpenner** [comment]
@thejameskyle this assumes NPM works correctly :P

**Comment by thejameskyle** [comment]
@stefanpenner that's the default operator for installs, it's used millions of times across every npm package. It's pretty stable :stuck_out_tongue_closed_eyes:

**Comment by stefanpenner** [comment]
you have much more faith in NPM then I.

**Pull request merged**
